import React, { useState, useEffect } from 'react';
import { CalendarPlus, BrainCircuit, Timer, X, Play, Pause, RotateCcw, Loader2 } from 'lucide-react';
import { generateFlashcards } from '../utils/ApiUtils';

export default function SurvivalToolbox({ result, isCooked }) {
  const [isFlashcardsLoading, setIsFlashcardsLoading] = useState(false);
  const [flashcards, setFlashcards] = useState(null);
  const [activeCard, setActiveCard] = useState(0);
  const [showAnswer, setShowAnswer] = useState(false);

  // Pomodoro State
  const [isTimerOpen, setIsTimerOpen] = useState(false);
  const [timeLeft, setTimeLeft] = useState(25 * 60);
  const [isRunning, setIsRunning] = useState(false);

  useEffect(() => {
    let interval;
    if (isRunning && timeLeft > 0) {
      interval = setInterval(() => setTimeLeft(t => t - 1), 1000);
    } else if (timeLeft === 0) {
      setIsRunning(false);
    }
    return () => clearInterval(interval);
  }, [isRunning, timeLeft]);

  const toggleTimer = () => setIsRunning(!isRunning);
  const resetTimer = () => { setIsRunning(false); setTimeLeft(25 * 60); };

  const handleGenerateFlashcards = async () => {
    if (!result) return;
    setIsFlashcardsLoading(true);
    try {
      const cards = await generateFlashcards(result);
      setFlashcards(cards);
      setActiveCard(0);
      setShowAnswer(false);
    } catch (e) {
      alert("Could not generate flashcards: " + e.message);
    } finally {
      setIsFlashcardsLoading(false);
    }
  };

  const nextCard = () => {
    setShowAnswer(false);
    setActiveCard((prev) => (prev + 1) % flashcards.length);
  };

  const handleCalendar = () => {
    // Basic ICS generation for a 2-hour generic study session
    const now = new Date();
    const end = new Date(now.getTime() + 2 * 60 * 60 * 1000); // 2 hours from now
    
    const formatDate = (date) => date.toISOString().replace(/-|:|\.\d+/g, '');
    
    const icsContent = `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//StudentOS//EN
BEGIN:VEVENT
DTSTART:${formatDate(now)}
DTEND:${formatDate(end)}
SUMMARY:Emergency Study Session
DESCRIPTION:Generated by StudentOS Survival Plan
END:VEVENT
END:VCALENDAR`;

    const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'study_session.ics';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  if (!result) return null;

  const accentStyles = isCooked 
    ? 'border-red-500/50 shadow-[0_0_20px_-5px_rgba(220,38,38,0.4)] bg-red-950/10' 
    : 'border-slate-700/50 shadow-lg bg-slate-800/40';

  const primaryBtn = isCooked
    ? 'bg-red-600 hover:bg-red-700 text-white border-transparent'
    : 'bg-indigo-600 hover:bg-indigo-700 text-white border-transparent';

  return (
    <div className={`rounded-xl p-3 sm:p-5 border ${accentStyles} transition-all duration-500`}>
      <h3 className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-4">Quick Actions</h3>
      <div className="flex flex-wrap gap-3">
        <button 
          onClick={handleCalendar}
          className={`flex items-center px-4 py-2 rounded-lg transition-colors text-sm font-medium border ${primaryBtn}`}
        >
          <CalendarPlus className="w-4 h-4 mr-2" />
          Add to Calendar
        </button>
        <button 
          onClick={handleGenerateFlashcards}
          disabled={isFlashcardsLoading}
          className="flex items-center px-4 py-2 bg-slate-700/50 hover:bg-slate-700 text-slate-200 rounded-lg transition-colors text-sm font-medium border border-slate-600/50 disabled:opacity-50"
        >
          {isFlashcardsLoading ? <Loader2 className="w-4 h-4 mr-2 animate-spin text-amber-400" /> : <BrainCircuit className="w-4 h-4 mr-2 text-amber-400" />}
          Generate Flashcards
        </button>
        <button 
          onClick={() => setIsTimerOpen(true)}
          className="flex items-center px-4 py-2 bg-slate-700/50 hover:bg-slate-700 text-slate-200 rounded-lg transition-colors text-sm font-medium border border-slate-600/50"
        >
          <Timer className="w-4 h-4 mr-2 text-rose-400" />
          Start Pomodoro
        </button>
      </div>

      {/* Flashcards UI */}
      {flashcards && flashcards.length > 0 && (
        <div className="mt-6 bg-slate-900/50 rounded-xl p-6 border border-amber-500/20 text-center relative">
          <button onClick={() => setFlashcards(null)} className="absolute top-3 right-3 text-slate-500 hover:text-white">
            <X className="w-5 h-5" />
          </button>
          <div className="text-xs font-mono text-slate-500 mb-2">Card {activeCard + 1} of {flashcards.length}</div>
          <div 
            onClick={() => setShowAnswer(!showAnswer)}
            className="min-h-[120px] flex items-center justify-center p-4 bg-slate-800 rounded-lg cursor-pointer hover:bg-slate-700 transition-colors"
          >
            <p className={`text-lg font-medium ${showAnswer ? 'text-amber-400' : 'text-slate-200'}`}>
              {showAnswer ? flashcards[activeCard].a : flashcards[activeCard].q}
            </p>
          </div>
          <div className="flex justify-between items-center mt-4">
            <p className="text-xs text-slate-500">Click card to flip</p>
            <button onClick={nextCard} className="px-4 py-1.5 bg-amber-500/20 text-amber-400 rounded-full text-sm font-medium hover:bg-amber-500/30 transition-colors">
              Next Card →
            </button>
          </div>
        </div>
      )}

      {/* Pomodoro Overlay */}
      {isTimerOpen && (
        <div className="fixed bottom-6 right-6 bg-slate-800 border border-rose-500/30 rounded-2xl p-6 shadow-2xl z-50 w-72">
          <button onClick={() => setIsTimerOpen(false)} className="absolute top-3 right-3 text-slate-500 hover:text-white">
            <X className="w-5 h-5" />
          </button>
          <div className="text-center">
            <h4 className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-1">Pomodoro</h4>
            <div className="text-5xl font-mono font-light text-rose-400 my-4 tracking-tight">
              {String(Math.floor(timeLeft / 60)).padStart(2, '0')}:{String(timeLeft % 60).padStart(2, '0')}
            </div>
            <div className="flex justify-center gap-3">
              <button onClick={toggleTimer} className="p-3 bg-rose-500/20 text-rose-400 rounded-full hover:bg-rose-500/30 transition-colors">
                {isRunning ? <Pause className="w-5 h-5" /> : <Play className="w-5 h-5 ml-1" />}
              </button>
              <button onClick={resetTimer} className="p-3 bg-slate-700/50 text-slate-300 rounded-full hover:bg-slate-700 transition-colors">
                <RotateCcw className="w-5 h-5" />
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
